#!/usr/bin/env python3
"""
Validate Second Brain files for Template A/B/C compliance.
Used by verify-second-brain agent.

Usage:
    python3 validate_template.py <filepath>
    python3 validate_template.py <filepath> --json

Exit codes:
    0 = Valid
    1 = Invalid (issues found)
    2 = Error (file not found, etc.)
"""

import sys
import re
import json
from pathlib import Path

# Required sections for Template A (Original Thinking)
REQUIRED_A = [
    'Metadata',
    'Summary',
    'Classification',
    'Keywords',
    'Source',
    'Status',
    'Original Text'
]

# Required sections for Template B (External References)
REQUIRED_B = [
    'Source',
    'Content',
    'Core Insight',
    'Relevance to My Thinking',
    'Keywords',
    'Attribution'
]

# Required sections for Template C (AI Synthesis)
REQUIRED_C = [
    'Metadata',
    'Summary',
    'Source Material',
    'Synthesized Text',
    'Classification',
    'Keywords',
    'Generation Context',
    'Status'
]

# Required metadata fields for Template A
METADATA_FIELDS_A = [
    'Source type',
    'Primary',
    'Projects',
    'Artifact status'
]

# Required metadata fields for Template C
METADATA_FIELDS_C = [
    'Source type',
    'Generated by',
    'Primary',
    'Projects',
    'Artifact status',
    'Review status'
]

# Template A folders (original thinking)
TEMPLATE_A_FOLDERS = [
    'Journal_Intellectual',
    'Journal_Personal',
    'Inventions',
    'Writing_SciFi',
    'Writing_AllElse',
    'Predictions',
    'Health',
    'Twitter_Personas',
    'Creative_AudioVisual',
    'To_Study'
]

# Template B folders (external references)
TEMPLATE_B_FOLDERS = [
    'External_Sources',
    'Reference'
]

# Template C folders (AI synthesis)
TEMPLATE_C_FOLDERS = [
    'Written_By_AI'
]


def detect_template(filepath: Path, content: str) -> str:
    """Detect whether file should be Template A, B, or C based on folder."""
    path_str = str(filepath)

    # Check Template C first (Written_By_AI folder)
    for folder in TEMPLATE_C_FOLDERS:
        if f'/{folder}/' in path_str or f'\\{folder}\\' in path_str:
            return 'C'

    # Fallback: content marker for Template C
    if '**Source type:** AI Synthesis' in content:
        return 'C'

    for folder in TEMPLATE_B_FOLDERS:
        if f'/{folder}/' in path_str or f'\\{folder}\\' in path_str:
            return 'B'

    for folder in TEMPLATE_A_FOLDERS:
        if f'/{folder}/' in path_str or f'\\{folder}\\' in path_str:
            return 'A'

    # Default: check content for Attribution section (Template B marker)
    if '## Attribution' in content:
        return 'B'

    return 'A'


def extract_sections(content: str) -> list:
    """Extract all ## section headers from markdown."""
    pattern = r'^##\s+(.+)$'
    sections = re.findall(pattern, content, re.MULTILINE)
    return [s.strip() for s in sections]


def extract_metadata_fields(content: str) -> list:
    """Extract **Field:** patterns from Metadata section."""
    # Find Metadata section
    match = re.search(r'## Metadata\n(.*?)(?=\n## |\Z)', content, re.DOTALL)
    if not match:
        return []

    metadata_content = match.group(1)
    pattern = r'\*\*([^*]+):\*\*'
    fields = re.findall(pattern, metadata_content)
    return [f.strip() for f in fields]


def check_original_text_preserved(content: str) -> bool:
    """Check if Original Text section has content."""
    match = re.search(r'## Original Text\n(.*?)(?=\n## |\Z)', content, re.DOTALL)
    if not match:
        return False

    text = match.group(1).strip()
    # Should have actual content, not just placeholder
    return len(text) > 10 and text not in ['[Preserved source material]', '[Original text here]']


def check_synthesized_text_present(content: str) -> bool:
    """Check if Synthesized Text section has content."""
    match = re.search(r'## Synthesized Text\n(.*?)(?=\n## |\Z)', content, re.DOTALL)
    if not match:
        return False

    text = match.group(1).strip()
    return len(text) > 10 and text not in ['[The AI-generated content]', '[Synthesized text here]']


def check_review_status(content: str) -> tuple:
    """Check if Review status field has a valid value. Returns (valid, value)."""
    match = re.search(r'\*\*Review status:\*\*\s*(.+)', content)
    if not match:
        return False, None

    value = match.group(1).strip()
    valid_values = ['Unread', 'Approved']
    return value in valid_values, value


def check_keywords_present(content: str) -> tuple:
    """Check Keywords section has actual keywords."""
    match = re.search(r'## Keywords\n(.*?)(?=\n## |\Z)', content, re.DOTALL)
    if not match:
        return False, 0

    keywords_text = match.group(1).strip()
    # Count comma-separated or newline-separated keywords
    if not keywords_text:
        return False, 0

    # Rough count
    keyword_count = len([k for k in re.split(r'[,\n]', keywords_text) if k.strip()])
    return keyword_count > 0, keyword_count


def validate_file(filepath: Path) -> dict:
    """Validate a single file. Returns validation result dict."""
    result = {
        'file': str(filepath),
        'valid': True,
        'template': None,
        'issues': [],
        'warnings': [],
        'sections_found': [],
        'sections_missing': []
    }

    if not filepath.exists():
        result['valid'] = False
        result['issues'].append(f'File not found: {filepath}')
        return result

    if not filepath.suffix == '.md':
        result['valid'] = False
        result['issues'].append('Not a markdown file')
        return result

    content = filepath.read_text(encoding='utf-8')

    # Detect template type
    template = detect_template(filepath, content)
    result['template'] = template

    # Get required sections based on template
    if template == 'A':
        required = REQUIRED_A
    elif template == 'C':
        required = REQUIRED_C
    else:
        required = REQUIRED_B

    # Extract sections
    sections = extract_sections(content)
    result['sections_found'] = sections

    # Check for missing sections
    for req in required:
        if not any(req.lower() in s.lower() for s in sections):
            result['sections_missing'].append(req)
            result['issues'].append(f'Missing required section: ## {req}')

    # Template A specific checks
    if template == 'A':
        # Check Metadata fields
        metadata_fields = extract_metadata_fields(content)
        for field in METADATA_FIELDS_A:
            if not any(field.lower() in f.lower() for f in metadata_fields):
                result['warnings'].append(f'Metadata missing field: {field}')

        # Check Original Text has content
        if 'Original Text' not in result['sections_missing']:
            if not check_original_text_preserved(content):
                result['warnings'].append('Original Text section appears empty or placeholder')

    # Template C specific checks
    elif template == 'C':
        # Check Metadata fields
        metadata_fields = extract_metadata_fields(content)
        for field in METADATA_FIELDS_C:
            if not any(field.lower() in f.lower() for f in metadata_fields):
                result['warnings'].append(f'Metadata missing field: {field}')

        # Check Synthesized Text has content
        if 'Synthesized Text' not in result['sections_missing']:
            if not check_synthesized_text_present(content):
                result['warnings'].append('Synthesized Text section appears empty or placeholder')

        # Check Review status value
        valid_status, status_value = check_review_status(content)
        if not valid_status:
            if status_value is None:
                result['warnings'].append('Review status field missing from Metadata')
            else:
                result['issues'].append(f'Review status must be Unread or Approved, got: {status_value}')

    # Check Keywords
    has_keywords, keyword_count = check_keywords_present(content)
    if not has_keywords:
        result['issues'].append('Keywords section is empty')
    elif keyword_count < 3:
        result['warnings'].append(f'Only {keyword_count} keywords found (recommend 5+)')

    # Check file has a title (# header)
    if not re.search(r'^# .+', content, re.MULTILINE):
        result['issues'].append('Missing title (# header)')

    # Set overall validity
    result['valid'] = len(result['issues']) == 0

    return result


def format_result(result: dict, as_json: bool = False) -> str:
    """Format validation result for output."""
    if as_json:
        return json.dumps(result, indent=2)

    lines = []
    status = '✓ VALID' if result['valid'] else '✗ INVALID'
    lines.append(f"{status} - Template {result['template']}")
    lines.append(f"File: {result['file']}")

    if result['issues']:
        lines.append("\nIssues:")
        for issue in result['issues']:
            lines.append(f"  ✗ {issue}")

    if result['warnings']:
        lines.append("\nWarnings:")
        for warning in result['warnings']:
            lines.append(f"  ⚠ {warning}")

    if result['sections_found']:
        lines.append(f"\nSections found: {len(result['sections_found'])}")

    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 validate_template.py <filepath> [--json]")
        sys.exit(2)

    filepath = Path(sys.argv[1])
    as_json = '--json' in sys.argv

    try:
        result = validate_file(filepath)
        print(format_result(result, as_json))
        sys.exit(0 if result['valid'] else 1)
    except Exception as e:
        if as_json:
            print(json.dumps({'error': str(e), 'valid': False}))
        else:
            print(f"Error: {e}")
        sys.exit(2)


if __name__ == '__main__':
    main()
